### ISSUE TITLE
Sorting By Type creates gap between same items

### ISSUE THREAD

**Issue by SamSchuddinck** [Goldenrevolver/QuickStackStore#15] opened 2023-07-10 14:43 UTC
When sorting a container (by type =default) it sometime creates a gap between items in containers.
This seems rather strange behaviour cause u expect them to be next to each other after sorting.

![ezgif com-optimize](https://github.com/Goldenrevolver/QuickStackStore/assets/6053379/2776811a-ee94-46e0-afc5-d4430c03290a)

**Comment by Goldenrevolver** [comment] 2023-10-07 20:28
the gif you sent shows behavior that is working as intended. the sorting is done from bottom left to top right, because that's how valheim by default goes through the slots (you can verify this by control moving items into a container). so the "gaps" you mentioned is simply a row break in sorting. you can change the behavior to work from top left to bottom right in the config. I do not support bottom right to top left or top left to bottom right

**Closed as completed by Goldenrevolver** 2023-10-07 20:28 UTC
